<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Name</name>
   <tag></tag>
   <elementGuidId>b264dd3d-4228-4837-89e0-d113fff277af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-form-field-infix.ng-tns-c79-10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/mat-form-field/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1aaa2f69-5b3a-4cec-8357-9144daec1ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-form-field-infix ng-tns-c79-10</value>
      <webElementGuid>7497aa54-a509-436e-9cb8-521b46907398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Name *</value>
      <webElementGuid>cbcee6b6-ff17-438f-b463-3e2cd5c4ea63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/mat-form-field[@class=&quot;mat-form-field ng-tns-c79-10 mat-primary WorkFlow full-width-field mat-form-field-type-mat-input mat-form-field-appearance-legacy mat-form-field-can-float mat-form-field-has-label mat-form-field-hide-placeholder ng-untouched ng-pristine ng-invalid ng-star-inserted&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c79-10&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c79-10&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c79-10&quot;]</value>
      <webElementGuid>ea38aaa2-f397-4749-b7e8-604cceb4472d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/mat-form-field/div/div/div</value>
      <webElementGuid>58df10c6-d64d-4a38-a424-db05fd315798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Visual Workflow'])[1]/following::div[8]</value>
      <webElementGuid>3d63b366-8f21-4d0d-a9a5-80294fe2c2c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ganga A'])[1]/following::div[11]</value>
      <webElementGuid>5dfc0e90-d5c7-437c-81ec-fc8ab99c7c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field/div/div/div</value>
      <webElementGuid>3911218c-ac19-460d-a9cd-dec030cb5733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Name *' or . = 'Name *')]</value>
      <webElementGuid>a18bf9c0-5842-4e3c-bdad-24b66fe4a13a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
