<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_iris_test.2810_test_tbl_saveclose-allow_9addf6</name>
   <tag></tag>
   <elementGuidId>e3abd7cc-a9bb-4e1e-80ef-7756947899ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.saveclose-allowed.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-1']/app-popup/div/div/div[2]/img[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>36d4d9c0-a7b1-4106-93f7-3e691429f761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mattooltip</name>
      <type>Main</type>
      <value>Save and Close</value>
      <webElementGuid>ddb0f800-872e-4a64-bae6-20bde8a8e2b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../../../assets/save_wrangle3.svg</value>
      <webElementGuid>0f01c2f4-2a71-4f12-a18d-ca66e563e1f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>saveclose-allowed ng-star-inserted</value>
      <webElementGuid>65b04350-df7b-4da2-963e-3e026a1cc976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cdk-describedby-message-1852</value>
      <webElementGuid>363c166e-72dc-4697-a534-d1b9ce476bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-1&quot;)/app-popup[@class=&quot;ng-star-inserted&quot;]/div[1]/div[@class=&quot;wrangle_page_header&quot;]/div[@class=&quot;title-actions&quot;]/img[@class=&quot;saveclose-allowed ng-star-inserted&quot;]</value>
      <webElementGuid>12b4a419-717f-4485-bb98-13c44eadd63d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-1']/app-popup/div/div/div[2]/img[2]</value>
      <webElementGuid>13f400fb-9cc1-4626-9081-39e38adcab3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img[2]</value>
      <webElementGuid>d15006c1-f619-481b-9d71-124e16744502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../../../../assets/save_wrangle3.svg']</value>
      <webElementGuid>a395684f-a771-48c1-b6e2-4723c5576ed8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
