<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Workflows</name>
   <tag></tag>
   <elementGuidId>fc21611e-33b8-4ed3-97a9-a39adb0df7e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.side-nav-menu.selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a268a0dc-1c1f-4d50-8dfe-02b2f76e1d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>side-nav-menu selected</value>
      <webElementGuid>03ce0a72-cb08-430b-9f57-c28cf6938140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Workflows</value>
      <webElementGuid>fe0742f5-be03-46af-85b5-f081aa408053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-workflow[@class=&quot;ng-star-inserted&quot;]/app-main-nav[1]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container sidenav-container&quot;]/mat-sidenav[@class=&quot;mat-drawer mat-sidenav sidenav ng-tns-c127-1 ng-trigger ng-trigger-transform mat-drawer-side mat-drawer-opened mat-sidenav-fixed ng-star-inserted&quot;]/div[@class=&quot;mat-drawer-inner-container ng-tns-c127-1&quot;]/mat-nav-list[@class=&quot;mat-nav-list mat-list-base allign_list ng-tns-c127-1&quot;]/a[@class=&quot;mat-list-item&quot;]/div[@class=&quot;mat-list-item-content&quot;]/span[@class=&quot;side-nav-menu selected&quot;]</value>
      <webElementGuid>f29cfd60-8565-4d11-8447-6bad9fdc82ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/following::span[1]</value>
      <webElementGuid>e0f36a96-a757-427d-84ee-ab370fa59d2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Functions'])[1]/preceding::span[1]</value>
      <webElementGuid>95a56ff2-bc53-44bd-8e11-e0c897452213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tags'])[1]/preceding::span[2]</value>
      <webElementGuid>22b6d884-b107-4df0-a1f5-0a2f00adbc05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Workflows']/parent::*</value>
      <webElementGuid>870622f9-e2b3-4535-b933-a147cdd5acbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div/span</value>
      <webElementGuid>4f5e8172-a2ba-4432-9e60-372d399f654d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Workflows' or . = 'Workflows')]</value>
      <webElementGuid>2eedf823-520c-4d55-88c2-f1edc7915959</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
