<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Wrangle</name>
   <tag></tag>
   <elementGuidId>3a5c29fd-231e-4e57-b6be-700aee391844</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn-create.mat-raised-button.mat-button-base.mat-primary.ng-star-inserted.cdk-focused.cdk-mouse-focused > span.mat-button-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-0']/app-wrangler-modal/div/div[2]/div[2]/div/div[2]/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7a9ddc79-6ad3-4c68-8ad7-9c3424b1b835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button-wrapper</value>
      <webElementGuid>082c413b-902b-40b6-9532-c21036b18f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Wrangle</value>
      <webElementGuid>dfedd1a5-1019-46ce-9ec7-8189bfe13df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)/app-wrangler-modal[@class=&quot;ng-star-inserted&quot;]/div[1]/div[@class=&quot;dialog_body_wrangle&quot;]/div[@class=&quot;radio-container&quot;]/div[@class=&quot;grid-container-two&quot;]/div[@class=&quot;grid-item&quot;]/div[1]/button[@class=&quot;btn-create mat-raised-button mat-button-base mat-primary ng-star-inserted cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]</value>
      <webElementGuid>580629da-8baa-42c8-b6de-6a919c00967d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/app-wrangler-modal/div/div[2]/div[2]/div/div[2]/div/button/span</value>
      <webElementGuid>ae6b3aa0-923c-454c-97c3-61c3f74aa5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh Schema'])[1]/preceding::span[1]</value>
      <webElementGuid>e1475d67-181d-4846-991d-313cc3ebe351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Columns selected:'])[1]/preceding::span[3]</value>
      <webElementGuid>03d07370-8543-41dd-9140-8ab81a03e12f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Wrangle']/parent::*</value>
      <webElementGuid>5e8b59ce-2732-455f-a58d-e558b9dee60d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/button/span</value>
      <webElementGuid>56c205d7-7647-4730-9185-39bd078dda28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Wrangle' or . = ' Wrangle')]</value>
      <webElementGuid>158f670d-5391-4015-bcce-a1fd249f18a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
