<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Python</name>
   <tag></tag>
   <elementGuidId>fbf0f1b9-1f4c-42fd-bf6c-a75191584d06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.language-type-holder > div:nth-of-type(2) > mat-radio-group.mat-radio-group > div.mr-5.ng-star-inserted.inactive-cluster > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Scala'])[1]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b7b2d32f-77e2-43a1-9bdb-39f0aca42dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Python</value>
      <webElementGuid>65463694-1a1f-4ee9-80f1-ff1b1dc2f47a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-job-form[@class=&quot;ng-star-inserted&quot;]/app-main-nav[1]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container sidenav-container mat-drawer-transition mat-drawer-container-has-open&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/div[@class=&quot;container&quot;]/div[2]/div[@class=&quot;grid-container&quot;]/div[@class=&quot;grid-item&quot;]/form[@class=&quot;ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;toggle-btns-holder&quot;]/div[@class=&quot;language-type-holder&quot;]/div[2]/mat-radio-group[@class=&quot;mat-radio-group&quot;]/div[@class=&quot;mr-5 ng-star-inserted inactive-cluster&quot;]/span[1]</value>
      <webElementGuid>c826a834-7cd5-4a71-ab7a-46af1c239415</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scala'])[1]/following::span[1]</value>
      <webElementGuid>a03f3aac-bc26-4947-a5c6-b1455275cb78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::span[2]</value>
      <webElementGuid>a3415cb4-b8bd-4f29-bf21-0b694d6111bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workflow Permissions'])[1]/preceding::span[1]</value>
      <webElementGuid>f848b9b7-767f-4d67-a357-9b0ca0323e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Private'])[1]/preceding::span[2]</value>
      <webElementGuid>9809eb97-b310-4e6f-8efc-aa84ace6580b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Python']/parent::*</value>
      <webElementGuid>bafd5fcb-6dee-45eb-b5c1-504c45e61c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/mat-radio-group/div[3]/span</value>
      <webElementGuid>650f70e1-9370-451a-83b4-8b33040f3bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Python' or . = 'Python')]</value>
      <webElementGuid>fb3d6b18-83b0-4460-a233-fc975f2dc635</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
