<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Databricks</name>
   <tag></tag>
   <elementGuidId>3edaab65-48d1-4d5a-8676-18aa94cb8334</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.exp-btn > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-35']/div/div/button/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ceb6b10c-2d40-431f-9c7f-fbd7eed3ea84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Databricks </value>
      <webElementGuid>59072781-bc88-4dce-ba5b-bf5fd7c1adbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-35&quot;)/div[@class=&quot;mat-menu-panel ng-trigger ng-trigger-transformMenu ng-tns-c111-58 mat-menu-after mat-menu-below ng-star-inserted mat-elevation-z4&quot;]/div[@class=&quot;mat-menu-content ng-tns-c111-58&quot;]/button[@class=&quot;mat-menu-item ng-tns-c111-58 cdk-focused cdk-mouse-focused&quot;]/div[@class=&quot;exp-btn&quot;]/span[1]</value>
      <webElementGuid>8c655b26-f65c-4512-8b6a-a5db401594a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-35']/div/div/button/div/span</value>
      <webElementGuid>1c9b0d71-0fee-433f-81d2-a9d29bfbeea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Row Count: NA'])[1]/following::span[1]</value>
      <webElementGuid>1ba2d7d4-d0bd-4adc-809a-dcd4ad10e525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Log'])[1]/following::span[4]</value>
      <webElementGuid>c5c1d218-98c4-4833-a92c-fcdb1aefb90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AWS S3/Athena'])[1]/preceding::span[1]</value>
      <webElementGuid>5e47a1a4-cab5-45ea-a6e8-1300943e91b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tableau Server'])[1]/preceding::span[2]</value>
      <webElementGuid>3d9e0e8e-930a-4ee3-8a5b-edbf5eab3a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/span</value>
      <webElementGuid>f4ec5109-56d5-4d0c-975c-eca734a04af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Databricks ' or . = ' Databricks ')]</value>
      <webElementGuid>3beff29f-09bc-4c6a-939d-71557231c786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::span[1]</value>
      <webElementGuid>b197d325-89c1-48de-9d97-951402fa04db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amazon EMR'])[1]/preceding::span[1]</value>
      <webElementGuid>4dbbf87f-fda2-4c4e-8eb2-a255caa30fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Snowflake'])[1]/preceding::span[2]</value>
      <webElementGuid>2ea3af27-8f85-478c-ba00-961b28af93b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Databricks']/parent::*</value>
      <webElementGuid>4498de8f-ca81-443e-8c2b-7a976ffef3e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-radio-group/div/span</value>
      <webElementGuid>93f5d266-39ed-421f-98e9-f96f0afac8e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Databricks' or . = 'Databricks')]</value>
      <webElementGuid>1c460608-b9f4-4f8c-83a8-bc2110d66686</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
