<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AWS</name>
   <tag></tag>
   <elementGuidId>0e1a2391-7203-40d3-98be-279c54e217a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-0']/nz-modal-container/div/div/div[2]/div/div/div[3]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ff4eecce-89f2-4578-a890-b7b021ac8bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-dropdown-trigger conn-item ng-star-inserted</value>
      <webElementGuid>b7763769-673f-4229-97e6-8846ec209b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> AWS </value>
      <webElementGuid>679a59aa-3ea3-404d-a661-ebd1629d3f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-0&quot;)/nz-modal-container[@class=&quot;ng-tns-c72-181 ng-trigger ng-trigger-modalContainer ant-modal-wrap ng-star-inserted&quot;]/div[@class=&quot;ant-modal ng-tns-c72-181&quot;]/div[@class=&quot;ant-modal-content ng-tns-c72-181&quot;]/div[@class=&quot;ant-modal-body ng-tns-c72-181&quot;]/div[@class=&quot;modal-content ng-star-inserted&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;gutter-row ant-col ant-col-8 ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ant-dropdown-trigger conn-item ng-star-inserted&quot;]</value>
      <webElementGuid>90b06f82-acbf-46da-bb25-c31f1fd200b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nztrigger</name>
      <type>Main</type>
      <value>click</value>
      <webElementGuid>a90a3ed9-799a-465c-b0f3-eb16c0064101</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-0']/nz-modal-container/div/div/div[2]/div/div/div[3]/div/div</value>
      <webElementGuid>89605e8c-ee24-4020-bf77-c8062f348b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salesforce'])[1]/following::div[3]</value>
      <webElementGuid>bd99b15f-e1cb-4667-8c7b-adbdb8d5ef8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RDBMS'])[1]/following::div[7]</value>
      <webElementGuid>3f613e19-2d32-4dfa-8612-c62a971c9266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Microsoft Azure'])[1]/preceding::div[2]</value>
      <webElementGuid>c0843de0-04c1-40e6-b53f-af02c8d985cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div</value>
      <webElementGuid>e1f5051f-8717-4c3b-98e6-237b5636e92e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' AWS ' or . = ' AWS ')]</value>
      <webElementGuid>47f1a675-6a26-4591-b555-93f05cc62eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-0']/nz-modal-container/div/div/div[2]/div/div/div[3]/div/div/div</value>
      <webElementGuid>8fab5300-0fff-412f-88ec-020e485d71ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salesforce'])[1]/following::div[4]</value>
      <webElementGuid>954cd16e-014d-4cd6-9ad9-bb880317a3f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RDBMS'])[1]/following::div[8]</value>
      <webElementGuid>17d2b9ed-d166-44b7-a021-b7252923df07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Microsoft Azure'])[1]/preceding::div[1]</value>
      <webElementGuid>0df1bde2-1837-44a0-8d9b-27388c7d5979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Google Cloud'])[1]/preceding::div[5]</value>
      <webElementGuid>bdd771e2-6f98-4f9b-bbe3-30565c041ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AWS']/parent::*</value>
      <webElementGuid>e437296a-5c65-40c4-babf-a8513186bd65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div</value>
      <webElementGuid>ad3c0ce3-2220-497f-b1a4-5e16821d2af0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
