<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_default</name>
   <tag></tag>
   <elementGuidId>87f3fffa-6a1f-4737-b92c-2db438879b6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nz-option-item.ant-select-item.ant-select-item-option.ng-star-inserted.ant-select-item-option-active > div.ant-select-item-option-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-16']/nz-option-container/div/cdk-virtual-scroll-viewport/div/nz-option-item[12]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e7d1385a-7248-420d-9408-b1874c2d50b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-item-option-content</value>
      <webElementGuid>09da6011-6875-42a4-b7c4-cf26c8de1554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>94ec1cad-a77d-4283-8f43-d5ce1b236775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-16&quot;)/nz-option-container[@class=&quot;ant-select-dropdown ng-tns-c133-230 ant-select-dropdown-placement-bottomLeft ng-trigger ng-trigger-slideMotion ng-star-inserted&quot;]/div[1]/cdk-virtual-scroll-viewport[@class=&quot;cdk-virtual-scroll-viewport cdk-virtual-scrollable cdk-virtual-scroll-orientation-vertical&quot;]/div[@class=&quot;cdk-virtual-scroll-content-wrapper&quot;]/nz-option-item[@class=&quot;ant-select-item ant-select-item-option ng-star-inserted ant-select-item-option-active&quot;]/div[@class=&quot;ant-select-item-option-content&quot;]</value>
      <webElementGuid>c3912b06-6706-4c8a-8cef-6684d3cb0250</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-16']/nz-option-container/div/cdk-virtual-scroll-viewport/div/nz-option-item[12]/div</value>
      <webElementGuid>6a1ba38b-e6b0-419a-821d-92f2c85da9b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dds_test_db'])[1]/following::div[1]</value>
      <webElementGuid>d7f2511f-9d1b-443b-a9a6-16fe8f9f1a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dds_ingestion_md_db'])[1]/following::div[2]</value>
      <webElementGuid>9df8fa9b-de3c-4112-abf2-42bf46d438cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='drg'])[1]/preceding::div[1]</value>
      <webElementGuid>9a3bc789-096b-45c8-8150-09dff7c67991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='drg_cfro'])[1]/preceding::div[2]</value>
      <webElementGuid>689ce6f5-954e-4003-bbe7-354c6a4d20a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='default']/parent::*</value>
      <webElementGuid>65ecb968-9361-4d6f-9126-62451eb885de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nz-option-item[12]/div</value>
      <webElementGuid>b412625e-08aa-453b-a527-89f1a5be0c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'default' or . = 'default')]</value>
      <webElementGuid>3734702b-7cff-4446-833b-4c383a0eeccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-15']/nz-option-container/div/cdk-virtual-scroll-viewport/div/nz-option-item[12]/div</value>
      <webElementGuid>726c27ef-3b05-4839-8214-e1ba27e90ac1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
