<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>51784742-4ec6-49e4-b49b-5d708316d857</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;folder&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='folder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>22750631-4dfc-4f5f-ac9d-660090065c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/image/folder.png</value>
      <webElementGuid>aae983b9-40a6-488b-aad2-fe707d24cfbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>folder</value>
      <webElementGuid>b8815b9c-3981-4c3a-986f-2da40f2cafa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/nz-layout[@class=&quot;ant-layout app-layout ant-layout-has-sider ng-star-inserted&quot;]/nz-layout[@class=&quot;ant-layout&quot;]/div[1]/nz-content[@class=&quot;nz_content ant-layout-content&quot;]/div[@class=&quot;inner-content&quot;]/app-add-workflow[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/nz-card[@class=&quot;ant-card ant-card-bordered ng-star-inserted&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;ant-row ng-star-inserted&quot;]/div[@class=&quot;ant-col ant-col-12&quot;]/app-source-connection-mapping[1]/div[@class=&quot;connection form ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/nz-form-item[@class=&quot;ant-row ant-form-item&quot;]/nz-form-control[@class=&quot;ng-tns-c189-189 ant-form-item-control ant-col ant-col-6 ant-col-xs-24 ant-col-sm-6 ng-star-inserted&quot;]/div[@class=&quot;ant-form-item-control-input ng-tns-c189-189&quot;]/div[@class=&quot;ant-form-item-control-input-content ng-tns-c189-189&quot;]/button[@class=&quot;ant-btn ng-tns-c189-189 ant-btn-link&quot;]/img[1]</value>
      <webElementGuid>20d440a5-3e7f-4fb8-8216-5719f756e83b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='folder']</value>
      <webElementGuid>eccde9b2-b8be-4a1e-bdc6-1b1511e48f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nz-form-control[2]/div/div/button/img</value>
      <webElementGuid>b0a0c1af-f131-4784-a51b-bc3346fda4aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/image/folder.png' and @alt = 'folder']</value>
      <webElementGuid>561be219-cf76-4da7-8e11-4a57482efa5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
