<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nz-option-item_True</name>
   <tag></tag>
   <elementGuidId>9b968df7-057d-4a1e-8979-d72004fcc503</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nz-option-item.ant-select-item.ant-select-item-option.ant-select-item-option-active.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-9']/nz-option-container/div/cdk-virtual-scroll-viewport/div/nz-option-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nz-option-item</value>
      <webElementGuid>0a18417b-c2f1-4efc-9a0c-9cfb0c8c5fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-item ant-select-item-option ant-select-item-option-active ng-star-inserted</value>
      <webElementGuid>04d84b07-aaa1-497f-aa9a-9b2597657754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>1017b9e5-63bf-43c1-ae1a-7d58c85ba0a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>d1bbeb79-5466-472a-b6c5-5fb165fa3495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-9&quot;)/nz-option-container[@class=&quot;ant-select-dropdown ng-tns-c133-199 ant-select-dropdown-placement-bottomLeft ng-trigger ng-trigger-slideMotion ng-star-inserted&quot;]/div[1]/cdk-virtual-scroll-viewport[@class=&quot;cdk-virtual-scroll-viewport cdk-virtual-scrollable cdk-virtual-scroll-orientation-vertical&quot;]/div[@class=&quot;cdk-virtual-scroll-content-wrapper&quot;]/nz-option-item[@class=&quot;ant-select-item ant-select-item-option ant-select-item-option-active ng-star-inserted&quot;]</value>
      <webElementGuid>3fe08a09-ee5a-4c79-a5f7-ca467f5eadb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-9']/nz-option-container/div/cdk-virtual-scroll-viewport/div/nz-option-item</value>
      <webElementGuid>ad73bc01-5ef1-4c6a-929f-75659c0e58f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::nz-option-item[1]</value>
      <webElementGuid>a1a630b6-98ae-4984-954b-df4e6529cc16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::nz-option-item[1]</value>
      <webElementGuid>d94b27ae-04db-4a21-8664-c4eb2981a10c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='False'])[1]/preceding::nz-option-item[1]</value>
      <webElementGuid>3227864b-f4be-4a72-ae73-b57fb3505134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nz-option-item</value>
      <webElementGuid>bfae6f59-2726-49cc-8e2d-46923ed7d387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nz-option-item[@title = 'True' and (text() = 'True' or . = 'True')]</value>
      <webElementGuid>7543aa63-0048-4200-b51d-ed31767801e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-8']/nz-option-container/div/cdk-virtual-scroll-viewport/div/nz-option-item</value>
      <webElementGuid>9b6058d7-5114-4b27-96aa-730a98d660fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
