<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nz-option-item_dcube-dds-terra-extractors-t_24962e</name>
   <tag></tag>
   <elementGuidId>82daf16d-f519-4432-82ac-9f799edd0540</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nz-option-item.ant-select-item.ant-select-item-option.ant-select-item-option-active.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-13']/nz-option-container/div/cdk-virtual-scroll-viewport/div/nz-option-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nz-option-item</value>
      <webElementGuid>782b43de-0f02-469b-99a4-09dadca7f852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-item ant-select-item-option ant-select-item-option-active ng-star-inserted</value>
      <webElementGuid>747d3879-dc83-4bdc-b74f-9be64895b4bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>dcube-dds-terra-extractors-target-test</value>
      <webElementGuid>02668b97-7417-4053-98b3-6184b0986d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>dcube-dds-terra-extractors-target-test</value>
      <webElementGuid>f1ff099f-48d5-4636-82b2-0fd742805aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-13&quot;)/nz-option-container[@class=&quot;ant-select-dropdown ng-tns-c133-208 ant-select-dropdown-placement-bottomLeft ng-trigger ng-trigger-slideMotion ng-star-inserted&quot;]/div[1]/cdk-virtual-scroll-viewport[@class=&quot;cdk-virtual-scroll-viewport cdk-virtual-scrollable cdk-virtual-scroll-orientation-vertical&quot;]/div[@class=&quot;cdk-virtual-scroll-content-wrapper&quot;]/nz-option-item[@class=&quot;ant-select-item ant-select-item-option ant-select-item-option-active ng-star-inserted&quot;]</value>
      <webElementGuid>3e8d1fbe-81db-4f86-8870-6fb144dd5f44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-13']/nz-option-container/div/cdk-virtual-scroll-viewport/div/nz-option-item</value>
      <webElementGuid>19db72ca-a9e5-4211-a105-495fcea883c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::nz-option-item[1]</value>
      <webElementGuid>cf3f4bff-8fd9-4a00-a340-909cd5c30b73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::nz-option-item[1]</value>
      <webElementGuid>1d1357ba-09b1-4b42-b9ed-eb04f137fda4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nz-option-item</value>
      <webElementGuid>16dad5c8-71f0-4f8b-a35a-45d56f9f7f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nz-option-item[@title = 'dcube-dds-terra-extractors-target-test' and (text() = 'dcube-dds-terra-extractors-target-test' or . = 'dcube-dds-terra-extractors-target-test')]</value>
      <webElementGuid>5c2158d6-9b2b-4ede-8bb2-9f96f3ccb9f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
