<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_decimal_test.csv</name>
   <tag></tag>
   <elementGuidId>a374bec2-d601-4287-9d19-62964c4a3092</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-8']/nz-modal-container/div/div/div[2]/div/div[2]/nz-tree/div[3]/div/nz-tree-node[10]/nz-tree-node-title/span/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>eec1a528-e515-4689-96d5-b83222493ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file-name</value>
      <webElementGuid>a721f855-c22c-4b29-a5cc-db8f8c9b22ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>decimal_test.csv</value>
      <webElementGuid>8c9a35fb-566d-4a75-8eaa-8b69f293bd36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-8&quot;)/nz-modal-container[@class=&quot;ng-tns-c72-201 ng-trigger ng-trigger-modalContainer ant-modal-wrap ng-star-inserted&quot;]/div[@class=&quot;ant-modal ng-tns-c72-201&quot;]/div[@class=&quot;ant-modal-content ng-tns-c72-201&quot;]/div[@class=&quot;ant-modal-body ng-tns-c72-201&quot;]/div[@class=&quot;modal-content ng-star-inserted&quot;]/div[@class=&quot;tree-container ng-star-inserted&quot;]/nz-tree[@class=&quot;nz_tree ng-tns-c247-202 ant-tree ant-tree-icon-hide ant-tree-block-node ng-star-inserted&quot;]/div[@class=&quot;ant-tree-list ng-tns-c247-202&quot;]/div[@class=&quot;ng-tns-c247-202 ant-tree-list-holder-inner ng-trigger ng-trigger-treeCollapseMotion ng-star-inserted&quot;]/nz-tree-node[@class=&quot;ng-tns-c247-202 ant-tree-treenode ng-star-inserted&quot;]/nz-tree-node-title[@class=&quot;ant-tree-node-content-wrapper&quot;]/span[@class=&quot;custom-node ng-star-inserted&quot;]/span[@class=&quot;ng-star-inserted&quot;]/span[@class=&quot;file-name&quot;]</value>
      <webElementGuid>ae928c9f-213f-4b1a-9a7c-b863cd4d5df5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-8']/nz-modal-container/div/div/div[2]/div/div[2]/nz-tree/div[3]/div/nz-tree-node[10]/nz-tree-node-title/span/span/span</value>
      <webElementGuid>66c04436-599d-41c9-a462-1efa548a7eac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='calendar.csv'])[1]/following::span[4]</value>
      <webElementGuid>db710930-c5ea-4336-9a4f-b8752361e87f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test_patient_details.csv'])[1]/following::span[8]</value>
      <webElementGuid>982cf80c-d51b-48ef-8ce7-5c34a2640b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='demo.csv'])[1]/preceding::span[2]</value>
      <webElementGuid>a833b412-5e1d-43bc-936f-bc879e4e9dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='switch_detail.csv'])[1]/preceding::span[6]</value>
      <webElementGuid>d706ee69-ee9c-4e2c-b871-f29820e919a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='decimal_test.csv']/parent::*</value>
      <webElementGuid>ce3148df-e819-4454-931c-f2f720e709e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nz-tree-node[10]/nz-tree-node-title/span/span/span</value>
      <webElementGuid>293c2ace-52e8-457f-ad32-0c7e2a6af0a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'decimal_test.csv' or . = 'decimal_test.csv')]</value>
      <webElementGuid>df3c6617-6ec1-48a6-8c5a-8b7658005549</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
