<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Date_Transformation.csv</name>
   <tag></tag>
   <elementGuidId>cd459525-6cf6-4a8e-b779-6454f8db39e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.file-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-7']/nz-modal-container/div/div/div[2]/div/div[2]/nz-tree/div[3]/div/nz-tree-node[2]/nz-tree-node-title/span/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>df298a8a-6d36-4627-b027-db8754845573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file-name</value>
      <webElementGuid>f1d1a259-7110-4598-bc7b-445e786c0585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Date_Transformation.csv</value>
      <webElementGuid>76f53e1b-0fc3-4065-bff5-6f95a350a2fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-7&quot;)/nz-modal-container[@class=&quot;ng-tns-c72-202 ng-trigger ng-trigger-modalContainer ant-modal-wrap ng-star-inserted&quot;]/div[@class=&quot;ant-modal ng-tns-c72-202&quot;]/div[@class=&quot;ant-modal-content ng-tns-c72-202&quot;]/div[@class=&quot;ant-modal-body ng-tns-c72-202&quot;]/div[@class=&quot;modal-content ng-star-inserted&quot;]/div[@class=&quot;tree-container ng-star-inserted&quot;]/nz-tree[@class=&quot;nz_tree ng-tns-c247-203 ant-tree ant-tree-icon-hide ant-tree-block-node ng-star-inserted&quot;]/div[@class=&quot;ant-tree-list ng-tns-c247-203&quot;]/div[@class=&quot;ng-tns-c247-203 ant-tree-list-holder-inner ng-trigger ng-trigger-treeCollapseMotion ng-star-inserted&quot;]/nz-tree-node[@class=&quot;ng-tns-c247-203 ant-tree-treenode ng-star-inserted&quot;]/nz-tree-node-title[@class=&quot;ant-tree-node-content-wrapper&quot;]/span[@class=&quot;custom-node ng-star-inserted&quot;]/span[@class=&quot;ng-star-inserted&quot;]/span[@class=&quot;file-name&quot;]</value>
      <webElementGuid>955de761-0640-4397-bd45-aae652e57fb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-7']/nz-modal-container/div/div/div[2]/div/div[2]/nz-tree/div[3]/div/nz-tree-node[2]/nz-tree-node-title/span/span/span</value>
      <webElementGuid>bf985fae-d26e-499a-9ebf-6726de694590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dcube-dds-terra-extractors-source-test'])[2]/following::span[4]</value>
      <webElementGuid>eb350e40-9d81-4f91-86dd-336202875a03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click to expand'])[1]/following::span[9]</value>
      <webElementGuid>80b42727-125b-4e96-b18b-62a2ffb2c91b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date_and_Numeric_Transformation.csv'])[1]/preceding::span[2]</value>
      <webElementGuid>a07bf448-d5ae-4f92-a4a8-9200065eb931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date_transformation.csv'])[1]/preceding::span[6]</value>
      <webElementGuid>4fe6dfae-6c3c-43bf-955e-8107e6405ba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Date_Transformation.csv']/parent::*</value>
      <webElementGuid>756c9dff-007c-4110-aa6e-6027694d7c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nz-tree-node[2]/nz-tree-node-title/span/span/span</value>
      <webElementGuid>0fd8d483-d3ab-4d72-bc38-3a2431d01d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Date_Transformation.csv' or . = 'Date_Transformation.csv')]</value>
      <webElementGuid>eeb77d7f-31cc-43b1-b8ec-8c8b47cf9280</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
