<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_dcube-dds-terra-extractors-target-test</name>
   <tag></tag>
   <elementGuidId>c727227e-c985-4fa1-9955-c5c4033a1107</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ant-select-item-option-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-12']/nz-option-container/div/cdk-virtual-scroll-viewport/div/nz-option-item/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>557edf83-89ea-4e3b-ae05-46458f58ebf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-item-option-content</value>
      <webElementGuid>cb83d850-56b3-4e20-8e70-1e340e598a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>dcube-dds-terra-extractors-target-test</value>
      <webElementGuid>c88a8afc-ce42-49ec-a778-87891c8ea8fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-12&quot;)/nz-option-container[@class=&quot;ant-select-dropdown ng-tns-c133-207 ant-select-dropdown-placement-bottomLeft ng-trigger ng-trigger-slideMotion ng-star-inserted&quot;]/div[1]/cdk-virtual-scroll-viewport[@class=&quot;cdk-virtual-scroll-viewport cdk-virtual-scrollable cdk-virtual-scroll-orientation-vertical&quot;]/div[@class=&quot;cdk-virtual-scroll-content-wrapper&quot;]/nz-option-item[@class=&quot;ant-select-item ant-select-item-option ant-select-item-option-active ng-star-inserted&quot;]/div[@class=&quot;ant-select-item-option-content&quot;]</value>
      <webElementGuid>b2a05641-a40a-4fc4-95f8-ee3f11ceaa9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-12']/nz-option-container/div/cdk-virtual-scroll-viewport/div/nz-option-item/div</value>
      <webElementGuid>05813f3d-6d3a-442c-bdae-acd143442c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::div[8]</value>
      <webElementGuid>454ded20-c5b4-4f9d-8284-a124e1b14daf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::div[8]</value>
      <webElementGuid>fa4cbc92-c14a-4a2c-a847-b6f65dcad494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='dcube-dds-terra-extractors-target-test']/parent::*</value>
      <webElementGuid>02402763-a5dc-4393-a53e-e3e487010a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nz-option-item/div</value>
      <webElementGuid>0bd25d94-e57e-45af-b73f-d2c232fe5478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'dcube-dds-terra-extractors-target-test' or . = 'dcube-dds-terra-extractors-target-test')]</value>
      <webElementGuid>d706039a-4601-4261-8808-c6782f042136</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
