<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_default</name>
   <tag></tag>
   <elementGuidId>cb0d9450-24dc-4f46-a857-45737fe269f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nz-option-item.ant-select-item.ant-select-item-option.ng-star-inserted.ant-select-item-option-active > div.ant-select-item-option-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-15']/nz-option-container/div/cdk-virtual-scroll-viewport/div/nz-option-item[12]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0f587f89-8b85-45d1-a97c-1ffed6928f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-item-option-content</value>
      <webElementGuid>c2dcb69f-04df-4538-a83c-8a17a8b9b5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>06d211ac-4747-4077-8c9c-df49c8dc2f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-15&quot;)/nz-option-container[@class=&quot;ant-select-dropdown ng-tns-c133-294 ant-select-dropdown-placement-bottomLeft ng-trigger ng-trigger-slideMotion ng-star-inserted&quot;]/div[1]/cdk-virtual-scroll-viewport[@class=&quot;cdk-virtual-scroll-viewport cdk-virtual-scrollable cdk-virtual-scroll-orientation-vertical&quot;]/div[@class=&quot;cdk-virtual-scroll-content-wrapper&quot;]/nz-option-item[@class=&quot;ant-select-item ant-select-item-option ng-star-inserted ant-select-item-option-active&quot;]/div[@class=&quot;ant-select-item-option-content&quot;]</value>
      <webElementGuid>69b90cc1-6e17-4dfd-9db1-5834be23f2a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-15']/nz-option-container/div/cdk-virtual-scroll-viewport/div/nz-option-item[12]/div</value>
      <webElementGuid>12fc6f81-2c2e-4de3-9889-3564b5a94718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dds_test_db'])[1]/following::div[1]</value>
      <webElementGuid>6cff66d0-2ca9-4692-9060-32505afc593a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dds_ingestion_md_db'])[1]/following::div[2]</value>
      <webElementGuid>a1188e6e-92a0-428a-82fa-42ef3933c62a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='drg'])[1]/preceding::div[1]</value>
      <webElementGuid>760da52a-c272-423f-94bf-96e074782f7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='drg_cfro'])[1]/preceding::div[2]</value>
      <webElementGuid>9b339d9d-16d1-49cc-b4a6-9a569cf0bb04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='default']/parent::*</value>
      <webElementGuid>6f3b6459-f31f-4379-92d4-815ccfe4ae2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nz-option-item[12]/div</value>
      <webElementGuid>46f8fbb5-2f20-41a6-bda1-e077a1ad4cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'default' or . = 'default')]</value>
      <webElementGuid>7e124990-4f11-4ae9-8057-e771b29c543f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
