<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Complete</name>
   <tag></tag>
   <elementGuidId>dcd73317-3ba0-4424-a385-d60028e10ab7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ant-select-item-option-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-13']/nz-option-container/div/cdk-virtual-scroll-viewport/div/nz-option-item/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3a40ebbf-7c68-447b-8b9e-0323f2aa439c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-item-option-content</value>
      <webElementGuid>91234040-9443-4f0c-96cf-d5e01e040e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Complete</value>
      <webElementGuid>680a4f03-6dfe-4dac-9e70-c90a7bfc7ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-13&quot;)/nz-option-container[@class=&quot;ant-select-dropdown ng-tns-c133-292 ant-select-dropdown-placement-bottomLeft ng-trigger ng-trigger-slideMotion ng-star-inserted&quot;]/div[1]/cdk-virtual-scroll-viewport[@class=&quot;cdk-virtual-scroll-viewport cdk-virtual-scrollable cdk-virtual-scroll-orientation-vertical&quot;]/div[@class=&quot;cdk-virtual-scroll-content-wrapper&quot;]/nz-option-item[@class=&quot;ant-select-item ant-select-item-option ant-select-item-option-active ng-star-inserted&quot;]/div[@class=&quot;ant-select-item-option-content&quot;]</value>
      <webElementGuid>ab08d892-4ec7-4fe6-957c-ed8beee6d64f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-13']/nz-option-container/div/cdk-virtual-scroll-viewport/div/nz-option-item/div</value>
      <webElementGuid>cf047fe6-75b1-4796-ba0e-05f181ed3b0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::div[8]</value>
      <webElementGuid>9109a472-a5eb-4a4a-973d-d52aaec385c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::div[8]</value>
      <webElementGuid>3b6f264e-3247-4a1f-ba60-bfd6c878a9d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Complete']/parent::*</value>
      <webElementGuid>e59af638-580d-40f1-b60d-54046fec2a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nz-option-item/div</value>
      <webElementGuid>beeb2fa9-aace-4a5d-82ae-2ef11d0b5c4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Complete' or . = 'Complete')]</value>
      <webElementGuid>55b5c676-7f48-4618-a863-40956bb9365b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
