<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Structured Files</name>
   <tag></tag>
   <elementGuidId>ea05ad7b-53ff-4769-8919-10759b6d54c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.name-div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-4']/nz-modal-container/div/div/div[2]/div/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>34e00f68-89c6-4c2e-b65a-5d3c583ac5e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>name-div</value>
      <webElementGuid>1396c8df-218c-4588-b96d-7ac86d802966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Structured Files </value>
      <webElementGuid>3460acfb-6ee8-4e35-b88b-fa3b3c2620d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-4&quot;)/nz-modal-container[@class=&quot;ng-tns-c72-192 ng-trigger ng-trigger-modalContainer ant-modal-wrap ng-star-inserted&quot;]/div[@class=&quot;ant-modal ng-tns-c72-192&quot;]/div[@class=&quot;ant-modal-content ng-tns-c72-192&quot;]/div[@class=&quot;ant-modal-body ng-tns-c72-192&quot;]/div[@class=&quot;modal-content ng-star-inserted&quot;]/div[@class=&quot;ant-row ant-row-bottom ant-row-space-around&quot;]/div[@class=&quot;ant-col ant-col-8 ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ant-dropdown-trigger conn-item ng-star-inserted&quot;]/div[@class=&quot;name-div&quot;]</value>
      <webElementGuid>65b2683c-3e50-4ab1-b94c-4380b943250f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-4']/nz-modal-container/div/div/div[2]/div/div/div/div/div/div</value>
      <webElementGuid>094266cc-784b-47fb-a667-cf5f8194970e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File Formats'])[1]/following::div[7]</value>
      <webElementGuid>2604ffb4-7da4-4538-80f7-ef6ac95eb981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::div[19]</value>
      <webElementGuid>10624bec-310a-4329-85d2-55fc773d0210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semi Structured'])[1]/preceding::div[1]</value>
      <webElementGuid>9ea1ef9c-ac57-4d63-8590-420f5f612bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unstructured Files'])[1]/preceding::div[5]</value>
      <webElementGuid>0fa5ce3f-feb6-4f1e-a75e-62f631a3ebd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Structured Files']/parent::*</value>
      <webElementGuid>ecda6151-39be-4783-96a2-73a94d1c79e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div</value>
      <webElementGuid>766113fe-dcb2-483b-8c1c-e9d76f0e6e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Structured Files ' or . = ' Structured Files ')]</value>
      <webElementGuid>fb2367ac-f4a3-4308-adc1-7f6fa60c0d12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
