<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>676ae85b-a374-4a21-93a1-824274c3c52b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;folder&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='folder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0a313f2f-514e-4e15-9ca6-310a2581de9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/image/folder.png</value>
      <webElementGuid>008a78c7-54f3-49e2-bad6-e074b9f44916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>folder</value>
      <webElementGuid>1b2baf3d-ba7f-4daa-9823-b61d289e3845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/nz-layout[@class=&quot;ant-layout app-layout ant-layout-has-sider ng-star-inserted&quot;]/nz-layout[@class=&quot;ant-layout&quot;]/div[1]/nz-content[@class=&quot;nz_content ant-layout-content&quot;]/div[@class=&quot;inner-content&quot;]/app-add-workflow[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/nz-card[@class=&quot;ant-card ant-card-bordered ng-star-inserted&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;ant-row ng-star-inserted&quot;]/div[@class=&quot;ant-col ant-col-12&quot;]/app-source-connection-mapping[1]/div[@class=&quot;connection form ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/nz-form-item[@class=&quot;ant-row ant-form-item&quot;]/nz-form-control[@class=&quot;ng-tns-c189-189 ant-form-item-control ant-col ant-col-6 ant-col-xs-24 ant-col-sm-6 ng-star-inserted&quot;]/div[@class=&quot;ant-form-item-control-input ng-tns-c189-189&quot;]/div[@class=&quot;ant-form-item-control-input-content ng-tns-c189-189&quot;]/button[@class=&quot;ant-btn ng-tns-c189-189 ant-btn-link&quot;]/img[1]</value>
      <webElementGuid>a87b96ba-38f7-4b9b-bbfc-f78648a56550</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='folder']</value>
      <webElementGuid>cec6f77a-8525-478f-b795-3d1018f33550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nz-form-control[2]/div/div/button/img</value>
      <webElementGuid>5d86651b-bc6f-49dc-88ab-d6dccc59a9a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/image/folder.png' and @alt = 'folder']</value>
      <webElementGuid>c13ce991-b59f-4a19-80f6-b6204f3b3478</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
