<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input_ul ant-input ng-tns-c189-188 n_16ae5f</name>
   <tag></tag>
   <elementGuidId>ca87081d-4ace-4d38-9b23-1c16ebcab12a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.input_ul.ant-input.ng-tns-c189-188.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>617b576b-0952-495b-a378-4572666f6815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>782db464-78e2-43fc-a536-02e01514fc90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>S3 file path</value>
      <webElementGuid>3768898f-62f1-4c2e-87ad-57c9bbeb9006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_ul ant-input ng-tns-c189-188 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>62350082-40e4-4682-a80a-bf9fafe779b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/nz-layout[@class=&quot;ant-layout app-layout ant-layout-has-sider ng-star-inserted&quot;]/nz-layout[@class=&quot;ant-layout&quot;]/div[1]/nz-content[@class=&quot;nz_content ant-layout-content&quot;]/div[@class=&quot;inner-content&quot;]/app-add-workflow[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/nz-card[@class=&quot;ant-card ant-card-bordered ng-star-inserted&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;ant-row ng-star-inserted&quot;]/div[@class=&quot;ant-col ant-col-12&quot;]/app-source-connection-mapping[1]/div[@class=&quot;connection form ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/nz-form-item[@class=&quot;ant-row ant-form-item&quot;]/nz-form-control[@class=&quot;ng-tns-c189-188 ant-form-item-control ant-col ant-col-8 ant-col-xs-24 ant-col-sm-8 ng-star-inserted&quot;]/div[@class=&quot;ant-form-item-control-input ng-tns-c189-188&quot;]/div[@class=&quot;ant-form-item-control-input-content ng-tns-c189-188&quot;]/input[@class=&quot;input_ul ant-input ng-tns-c189-188 ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>6a6f5884-480c-4ca4-bf94-221c670d808b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>69b2c814-5558-4371-8bb3-e7f4307e19d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>2bb60715-5e52-488f-8a91-60b8d8d349b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'S3 file path']</value>
      <webElementGuid>daf47863-40e4-48e2-a084-ce9946ca7961</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
