<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ga_ant-input ng-untouched ng-pristine_92c671</name>
   <tag></tag>
   <elementGuidId>20290d2d-fa29-416f-8852-79d1f24b2c8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ant-input.ng-untouched.ng-pristine.ng-valid.ant-input-lg.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ea5f277-dfbf-443e-8a3e-9474a861585f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>fe6b1423-5b53-49af-8e14-ecbe081cfdca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ng-untouched ng-pristine ng-valid ant-input-lg ng-star-inserted</value>
      <webElementGuid>4d86431c-2d96-449c-819c-3707be5278eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/nz-layout[@class=&quot;ant-layout app-layout ant-layout-has-sider ng-star-inserted&quot;]/nz-layout[@class=&quot;ant-layout&quot;]/div[1]/nz-content[@class=&quot;nz_content ant-layout-content&quot;]/div[@class=&quot;inner-content&quot;]/app-workflow-list[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ant-row mb-1&quot;]/div[@class=&quot;ant-col ant-col-6&quot;]/nz-input-group[@class=&quot;ant-input-affix-wrapper ant-input-affix-wrapper-lg cdk-focused cdk-mouse-focused ant-input-affix-wrapper-focused&quot;]/input[@class=&quot;ant-input ng-untouched ng-pristine ng-valid ant-input-lg ng-star-inserted&quot;]</value>
      <webElementGuid>373afee2-9ccf-4e85-be84-9aea7c927913</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>88b6b83a-45b7-4a04-9ee7-9857d1d62f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search']</value>
      <webElementGuid>a1462541-18c5-4d18-ae44-fe13ee801f65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
