<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nz-option-item_dcube-dds-terra-extractors-s_be1768</name>
   <tag></tag>
   <elementGuidId>db2369e4-2792-4e73-be39-949abeab56a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nz-option-item.ant-select-item.ant-select-item-option.ant-select-item-option-active.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-3']/nz-option-container/div/cdk-virtual-scroll-viewport/div/nz-option-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nz-option-item</value>
      <webElementGuid>c8f5e462-7468-4c11-af6e-1124dc27c248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-item ant-select-item-option ant-select-item-option-active ng-star-inserted</value>
      <webElementGuid>0130a540-9e1a-49c5-8421-a8d5188fbb47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>dcube-dds-terra-extractors-source-test</value>
      <webElementGuid>375b58c4-6e72-4686-be59-1eee737956e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>dcube-dds-terra-extractors-source-test</value>
      <webElementGuid>84ae1250-52ef-45c9-8771-f16663f0bf04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-3&quot;)/nz-option-container[@class=&quot;ant-select-dropdown ng-tns-c133-187 ant-select-dropdown-placement-bottomLeft ng-trigger ng-trigger-slideMotion ng-star-inserted&quot;]/div[1]/cdk-virtual-scroll-viewport[@class=&quot;cdk-virtual-scroll-viewport cdk-virtual-scrollable cdk-virtual-scroll-orientation-vertical&quot;]/div[@class=&quot;cdk-virtual-scroll-content-wrapper&quot;]/nz-option-item[@class=&quot;ant-select-item ant-select-item-option ant-select-item-option-active ng-star-inserted&quot;]</value>
      <webElementGuid>a4a2fec9-e0e0-481b-90a4-ef9e88db6e46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-3']/nz-option-container/div/cdk-virtual-scroll-viewport/div/nz-option-item</value>
      <webElementGuid>e4efc05c-48bb-49c0-a4b0-77228100fccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::nz-option-item[1]</value>
      <webElementGuid>b20d51cc-ae29-4c19-8d03-d66339a3b6d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::nz-option-item[1]</value>
      <webElementGuid>f8203d7f-c05d-4c7e-a250-2dabf861b601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nz-option-item</value>
      <webElementGuid>ae8cae51-dfa2-4bdb-a05a-8d71b050517b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nz-option-item[@title = 'dcube-dds-terra-extractors-source-test' and (text() = 'dcube-dds-terra-extractors-source-test' or . = 'dcube-dds-terra-extractors-source-test')]</value>
      <webElementGuid>fed5765c-bc61-4c58-b980-222bc47cac2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
