<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_calendar.csv</name>
   <tag></tag>
   <elementGuidId>8bbf4304-8bf7-4795-8a21-37358eef19d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-7']/nz-modal-container/div/div/div[2]/div/div[2]/nz-tree/div[3]/div/nz-tree-node[9]/nz-tree-node-title/span/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8ea4ebd5-96c1-4e88-8d90-6a2c9b82fa2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file-name</value>
      <webElementGuid>5f59adb9-f263-4053-81a0-113826e76a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>calendar.csv</value>
      <webElementGuid>5f0a158c-2c6f-48a4-95fd-4d903d0ccb5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-7&quot;)/nz-modal-container[@class=&quot;ng-tns-c72-200 ng-trigger ng-trigger-modalContainer ant-modal-wrap ng-star-inserted&quot;]/div[@class=&quot;ant-modal ng-tns-c72-200&quot;]/div[@class=&quot;ant-modal-content ng-tns-c72-200&quot;]/div[@class=&quot;ant-modal-body ng-tns-c72-200&quot;]/div[@class=&quot;modal-content ng-star-inserted&quot;]/div[@class=&quot;tree-container ng-star-inserted&quot;]/nz-tree[@class=&quot;nz_tree ng-tns-c247-201 ant-tree ant-tree-icon-hide ant-tree-block-node ng-star-inserted&quot;]/div[@class=&quot;ant-tree-list ng-tns-c247-201&quot;]/div[@class=&quot;ng-tns-c247-201 ant-tree-list-holder-inner ng-trigger ng-trigger-treeCollapseMotion ng-star-inserted&quot;]/nz-tree-node[@class=&quot;ng-tns-c247-201 ant-tree-treenode ng-star-inserted&quot;]/nz-tree-node-title[@class=&quot;ant-tree-node-content-wrapper&quot;]/span[@class=&quot;custom-node ng-star-inserted&quot;]/span[@class=&quot;ng-star-inserted&quot;]/span[@class=&quot;file-name&quot;]</value>
      <webElementGuid>c418a5f9-ecf3-4437-9a43-5ac0e2225957</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-7']/nz-modal-container/div/div/div[2]/div/div[2]/nz-tree/div[3]/div/nz-tree-node[9]/nz-tree-node-title/span/span/span</value>
      <webElementGuid>1f14bc3b-d3b9-44ea-b507-ea3e7df822c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test_patient_details.csv'])[1]/following::span[4]</value>
      <webElementGuid>76a63c9c-68ea-4681-90ca-ffd5f532764d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test_decimal_team.csv'])[1]/following::span[8]</value>
      <webElementGuid>be867b12-ad4d-42f8-9890-fdb543bd81f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='decimal_test.csv'])[1]/preceding::span[2]</value>
      <webElementGuid>db30602c-df5c-48a0-8dda-a91541458368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='demo.csv'])[1]/preceding::span[6]</value>
      <webElementGuid>f964da12-b951-40b3-96d2-7ba9ea83d80f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='calendar.csv']/parent::*</value>
      <webElementGuid>83d8c214-bb65-463b-a1b3-43bb3468d07e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nz-tree-node[9]/nz-tree-node-title/span/span/span</value>
      <webElementGuid>14a54b1e-814e-4290-8e58-799569a98087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'calendar.csv' or . = 'calendar.csv')]</value>
      <webElementGuid>1e2d4f4c-e3cb-429f-be17-80368672b0ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
