<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>65bf9866-d3a7-4040-af26-cc10f21a7a09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.anticon.ant-tree-switcher-icon.anticon-caret-down.ng-star-inserted > svg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Click to expand'])[1]/following::*[name()='svg'][2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>934cbdd4-cb74-45f5-adf7-65a59043a278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 1024 1024</value>
      <webElementGuid>7a7aafef-ca06-49c7-9f54-52f175ed05f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9d225bf9-6f23-431d-8a9e-6d3d6b596c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>45a1df0f-0c8e-4708-839c-d1f6a7bfea02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>23980c1f-9bd3-4dbd-b1bc-9a6ae62353da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>c65baf1a-c0fc-48a6-b289-bcd9df6f6f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>caret-down</value>
      <webElementGuid>635820c5-0698-4d60-bbb8-4020f34f5dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b2518ce6-e176-4500-ab0f-e20549674994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-7&quot;)/nz-modal-container[@class=&quot;ng-tns-c72-200 ng-trigger ng-trigger-modalContainer ant-modal-wrap ng-star-inserted&quot;]/div[@class=&quot;ant-modal ng-tns-c72-200&quot;]/div[@class=&quot;ant-modal-content ng-tns-c72-200&quot;]/div[@class=&quot;ant-modal-body ng-tns-c72-200&quot;]/div[@class=&quot;modal-content ng-star-inserted&quot;]/div[@class=&quot;tree-container ng-star-inserted&quot;]/nz-tree[@class=&quot;nz_tree ng-tns-c247-201 ant-tree ant-tree-icon-hide ant-tree-block-node ng-star-inserted&quot;]/div[@class=&quot;ant-tree-list ng-tns-c247-201&quot;]/div[@class=&quot;ng-tns-c247-201 ant-tree-list-holder-inner ng-animate-disabled ng-trigger ng-trigger-treeCollapseMotion ng-star-inserted&quot;]/nz-tree-node[@class=&quot;ng-tns-c247-201 ant-tree-treenode ant-tree-treenode-switcher-close ng-star-inserted&quot;]/nz-tree-node-switcher[@class=&quot;ant-tree-switcher ant-tree-switcher_close ng-star-inserted&quot;]/span[@class=&quot;anticon ant-tree-switcher-icon anticon-caret-down ng-star-inserted&quot;]/svg[1]</value>
      <webElementGuid>a2bad96d-58d9-4735-855c-053218df2e5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click to expand'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>b479416d-9a93-4e5f-9b41-f6ffae87b206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show all files'])[1]/following::*[name()='svg'][3]</value>
      <webElementGuid>e9190990-f9d4-4d39-bfcd-d9886e4917a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dcube-dds-terra-extractors-source-test'])[2]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>82dc16d5-f516-44d7-9880-637dfc0fee82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>66b16545-c038-4007-b863-e80ad94277fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
