<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__input_ul small ant-input ng-tns-c_992033</name>
   <tag></tag>
   <elementGuidId>c1b42c21-61c6-45af-aeea-a69c0621c979</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.input_ul.small.ant-input.ng-tns-c189-163.ng-untouched.ng-valid.ant-input-status-success.ng-dirty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b353d688-bff4-4260-9cd8-1a85d76bbc25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7f63bba1-73c5-4d52-b28a-167f72e2f1df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>953e5053-1388-4d1e-9dc9-fa02aac6f442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Max length 100 characters</value>
      <webElementGuid>794ae29c-4090-4dc8-ad31-91af4e1dc0d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_ul small ant-input ng-tns-c189-163 ng-untouched ng-valid ant-input-status-success ng-dirty</value>
      <webElementGuid>dc2f0d5e-8e72-4426-a0a5-bbdb3a00d4b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/nz-layout[@class=&quot;ant-layout app-layout ant-layout-has-sider ng-star-inserted&quot;]/nz-layout[@class=&quot;ant-layout&quot;]/div[1]/nz-content[@class=&quot;nz_content ant-layout-content&quot;]/div[@class=&quot;inner-content&quot;]/app-add-workflow[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/nz-card[@class=&quot;ant-card ant-card-bordered ng-star-inserted&quot;]/div[@class=&quot;ant-card-body&quot;]/app-create-workflow[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ant-row create-workflow-div&quot;]/div[@class=&quot;ant-col ant-col-18 ant-col-offset-5&quot;]/div[1]/nz-form-item[@class=&quot;ant-row ant-form-item ant-form-item-has-success&quot;]/nz-form-control[@class=&quot;ng-tns-c189-163 ant-form-item-control ant-col ant-col-xs-24 ant-col-sm-14 ng-star-inserted&quot;]/div[@class=&quot;ant-form-item-control-input ng-tns-c189-163&quot;]/div[@class=&quot;ant-form-item-control-input-content ng-tns-c189-163&quot;]/textarea[@class=&quot;input_ul small ant-input ng-tns-c189-163 ng-untouched ng-valid ant-input-status-success ng-dirty&quot;]</value>
      <webElementGuid>bd644bfc-1f62-4111-9e6c-8d99f179d5f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>26351411-9440-44b3-8d35-e3a40bdeba67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Max length 100 characters']</value>
      <webElementGuid>2e99c502-507c-475e-a8b6-1c8312c98eac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
