<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>0dfd112c-e408-45a7-add4-8f9af8da1447</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.cdk-focused.cdk-mouse-focused > div.btn-create-visual > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7492de87-4854-40f8-82ca-b0f220fd6b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../assets/plus.png</value>
      <webElementGuid>8ffd77db-8c67-4265-913c-192d673d7cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-workflow-list[@class=&quot;ng-star-inserted&quot;]/app-main-nav[1]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container sidenav-container&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/div[@class=&quot;table_align&quot;]/app-workflow-table[1]/div[1]/div[1]/div[@class=&quot;grid-container&quot;]/div[@class=&quot;grid-item&quot;]/div[1]/div[2]/div[2]/a[@class=&quot;cdk-focused cdk-mouse-focused&quot;]/div[@class=&quot;btn-create-visual&quot;]/img[1]</value>
      <webElementGuid>180a500d-a243-4f8d-bc1a-e9c044942aa5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/div/img</value>
      <webElementGuid>372b87b1-379d-4a80-9d89-3a2ab1677125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../assets/plus.png']</value>
      <webElementGuid>7f9a17b7-1164-4972-8fdc-507dab31ec43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
