<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>3afe44f4-aab3-4bf4-bb85-b412092923bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;filter&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='filter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5810c85d-8e9a-45a6-bb9c-26454728b50a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>filter</value>
      <webElementGuid>45328881-cd28-49be-ad98-61800a741133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../assets/iris_icons/Landing_Page/SVG/filter.svg</value>
      <webElementGuid>d86066d2-e66c-4923-bad4-7cedeb278375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-workflow-list[@class=&quot;ng-star-inserted&quot;]/app-main-nav[1]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container sidenav-container&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/div[@class=&quot;table_align&quot;]/app-workflow-table[1]/div[1]/div[1]/div[@class=&quot;grid-container&quot;]/div[@class=&quot;grid-item&quot;]/img[1]</value>
      <webElementGuid>a37da5e7-3cc8-42e4-88ae-39727ecf470e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='filter']</value>
      <webElementGuid>7aefd479-187f-48cd-a51c-4a1d35d44d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/img</value>
      <webElementGuid>b8cd805f-c1d7-4d55-a3c1-9765f4f4463c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'filter' and @src = '../../assets/iris_icons/Landing_Page/SVG/filter.svg']</value>
      <webElementGuid>ba5bcc93-a329-49bc-9819-974e96fd78b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
