<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_NA_workflow_actions icon-hover</name>
   <tag></tag>
   <elementGuidId>96289abb-c639-46f1-9848-53074dfe890d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e05fbfc5-a07e-45ef-b3c3-25bc16c76073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mattooltip</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>d2046f85-a486-44cc-8b6c-397b33df32d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>warn</value>
      <webElementGuid>6210689f-dd3e-4f9c-88e2-f885938fb101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../assets/new_icons/DeleteIcon.svg</value>
      <webElementGuid>dd8e24fb-9e8c-4576-bf35-c152b93de067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>workflow_actions icon-hover</value>
      <webElementGuid>6f636d27-23f5-4a6c-b813-f0118f8508e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cdk-describedby-message-32</value>
      <webElementGuid>1731de04-b567-461e-baac-7ff6561f1102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-workflow-list[@class=&quot;ng-star-inserted&quot;]/app-main-nav[1]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container sidenav-container&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/div[@class=&quot;table_align&quot;]/app-workflow-table[1]/div[@class=&quot;mat-elevation-z8&quot;]/table[@class=&quot;mat-table cdk-table full-width-table&quot;]/tbody[1]/tr[@class=&quot;mat-row cdk-row ng-star-inserted&quot;]/td[@class=&quot;mat-cell cdk-cell cdk-column-action mat-column-action ng-star-inserted&quot;]/div[1]/img[@class=&quot;workflow_actions icon-hover&quot;]</value>
      <webElementGuid>f8b7528b-872d-4306-90ab-d1e34658d9ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[6]</value>
      <webElementGuid>f6cece4b-6ffa-4e0f-9352-18e6cac484ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../assets/new_icons/DeleteIcon.svg']</value>
      <webElementGuid>e31a0965-27e9-4134-85b3-b14f036db678</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
